// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEq9ghaq7kCCtcVkxAlxVxcS9N2pzJVPA',
    appId: '1:475553539446:web:4e40786b3ac24c94e04657',
    messagingSenderId: '475553539446',
    projectId: 'pethomeconnect',
    authDomain: 'pethomeconnect.firebaseapp.com',
    databaseURL: 'https://pethomeconnect-default-rtdb.firebaseio.com',
    storageBucket: 'pethomeconnect.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXEaPmKKJTkN23vnft6tNVhzz_qFtCz2A',
    appId: '1:475553539446:android:dae94ca77f65a60ae04657',
    messagingSenderId: '475553539446',
    projectId: 'pethomeconnect',
    databaseURL: 'https://pethomeconnect-default-rtdb.firebaseio.com',
    storageBucket: 'pethomeconnect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR3LLbx-QAIAiWmhYPAlmktppUF2_CWds',
    appId: '1:475553539446:ios:86be9f14bff02d84e04657',
    messagingSenderId: '475553539446',
    projectId: 'pethomeconnect',
    databaseURL: 'https://pethomeconnect-default-rtdb.firebaseio.com',
    storageBucket: 'pethomeconnect.appspot.com',
    iosClientId: '475553539446-bcbb0o75ekgkrjhse08nfaveq6lol3cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.pethomeConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR3LLbx-QAIAiWmhYPAlmktppUF2_CWds',
    appId: '1:475553539446:ios:86be9f14bff02d84e04657',
    messagingSenderId: '475553539446',
    projectId: 'pethomeconnect',
    databaseURL: 'https://pethomeconnect-default-rtdb.firebaseio.com',
    storageBucket: 'pethomeconnect.appspot.com',
    iosClientId: '475553539446-bcbb0o75ekgkrjhse08nfaveq6lol3cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.pethomeConnect',
  );
}
