// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmSY5DNZMsXpQ5kJ8o1hvQ2UIliLW4M8w',
    appId: '1:640501216685:web:601f8ca8eead0966751d24',
    messagingSenderId: '640501216685',
    projectId: 'pethome-connect-api',
    authDomain: 'pethome-connect-api.firebaseapp.com',
    storageBucket: 'pethome-connect-api.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK6-M02DSodCyXcbsTHw0Q74i1lnP1WoE',
    appId: '1:640501216685:android:2a265ae2ec7f9a00751d24',
    messagingSenderId: '640501216685',
    projectId: 'pethome-connect-api',
    storageBucket: 'pethome-connect-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYnRYudw-n6rl4zbmwb_fiGhKty5Glhkw',
    appId: '1:640501216685:ios:517c61687aa84ca5751d24',
    messagingSenderId: '640501216685',
    projectId: 'pethome-connect-api',
    storageBucket: 'pethome-connect-api.appspot.com',
    iosClientId: '640501216685-6nfbs4660s81n1j35rucvira1lkfbdod.apps.googleusercontent.com',
    iosBundleId: 'com.example.pethomeConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYnRYudw-n6rl4zbmwb_fiGhKty5Glhkw',
    appId: '1:640501216685:ios:517c61687aa84ca5751d24',
    messagingSenderId: '640501216685',
    projectId: 'pethome-connect-api',
    storageBucket: 'pethome-connect-api.appspot.com',
    iosClientId: '640501216685-6nfbs4660s81n1j35rucvira1lkfbdod.apps.googleusercontent.com',
    iosBundleId: 'com.example.pethomeConnect',
  );
}
